name: CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest


    steps:

    - uses: actions/checkout@v2
      
    - name: Use Java 11
      uses: actions/setup-java@v2
      with:
          distribution: 'temurin'
          java-version: '11'

    - name: Build debug apk
      run: ./gradlew clean assembleDebug
